### PR TITLE
bzz-link: add support for ens subdomains

### PR DESCRIPTION
**Pull request by darkobas2**

### CODE REVIEW

**Comment by AuHau** [comment]
@agazso refresh my memory please. If I remember correctly we did not support ENS subdomains because it is not possible to get wildercard sub-subdomain certificate for HTTPS? Or there was something related to that, is that relevant here?

**Comment by darkobas2** [comment]
> @agazso refresh my memory please. If I remember correctly we did not support ENS subdomains because it is not possible to get wildercard sub-subdomain certificate for HTTPS? Or there was something related to that, is that relevant here?

Sorry to barge in. If you know the first level domain name then you can get a working certificate for subdomains.
Lets I want to host my site on swarm i setup my own bzz link service to swarm ie. Web2.org    so my swarm site would be  accessible via ens_name.web2.org   and because i know this i can get a *.ens_name.web2.org cert for the subdomains

**Comment by AuHau** [comment]
> Sorry to barge in. If you know the first level domain name then you can get a working certificate for subdomains. Lets I want to host my site on swarm i setup my own bzz link service to swarm ie. Web2.org so my swarm site would be accessible via ens_name.web2.org and because i know this i can get a *.ens_name.web2.org cert for the subdomains

No sorry needed 😉 So if I understand your use-case correctly, you would want to host ENS subdomains for fixed ENS name right? What do you expect to happen if a user would enter some other ENS name like `other_ens_name.web2.org`? Would you have directed to the gateway-proxy only the DNS subdomain entry for `ens_name` and with that ensuring that only the desired ENS name is used?

**Comment by darkobas2** [comment]
@AuHau yes. My use case is hosting a private setup not a public bzz.link you are used to :). And yes therefore other_ens_name wouldnt even be resolved

**Comment by darkobas2** [comment]
closing in favor of cleaner: https://github.com/ethersphere/gateway-proxy/pull/328

**Pull request closed without merging**
